name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
    paths:
      - '**.go'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version-file: 'go.mod'
      - name: Build UI
        run: make ui
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: 'latest'
